apiVersion: v1
kind: Secret
metadata:
  name: sample-mariadb-secret
type: Opaque
stringData:
  haproxy.cfg: |-
    global
      log /dev/log local0
      log /dev/log local1 notice
      stats timeout 30s
      pidfile /var/run/haproxy/haproxy.pid
      daemon
    defaults
      maxconn 20000
      timeout connect 5000
      timeout client  50000
      timeout server  50000
    # frontend, stats
    listen haproxy-monitoring
      bind 0.0.0.0:80
      mode http
      stats enable
      stats show-legends
      stats refresh 5s
      stats uri /
      stats realm Haproxy\ Statistics
      stats auth haproxy:hpr0x1
      stats admin if TRUE
    frontend haproxy
      bind 0.0.0.0:3306
      default_backend galera_cluster
    # mysql
    backend galera_cluster
      mode tcp
      balance roundrobin
      option mysql-check user haproxy_check
      server mariadb01.internal.site 172.16.0.201:3306 check
      server mariadb02.internal.site 172.16.0.202:3306 check
      server mariadb03.internal.site 172.16.0.203:3306 check    
